### ISSUE TITLE
[bug] ascii' codec can't encode characters in position 16-24

### ISSUE THREAD

**Issue by thinkycx** [fuergaosi233/gitbook2pdf#31]
ubuntu 18.04
python 3.6.7

$ python3 gitbook.py http://hukai.me/android-training-course-in-chinese/

```
Traceback (most recent call last):
  File "gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 205, in run
    self.write_pdf(self.fname, html_text, css_text)
  File "gitbook.py", line 246, in write_pdf
    with open(htmlname, 'w', encoding='utf-8') as f:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-24: ordinal not in range(128)
```

$ python3 gitbook.py http://self-publishing.ebookchain.org
```
crawling :  crawling :  crawling :  crawling :  crawling :  crawling :  crawling :  crawling :  crawling :  http://self-publishing.ebookchain.org/index.html
crawling :  crawling :  crawling :  Traceback (most recent call last):
  File "gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 192, in run
    loop.run_until_complete(self.crawl_main_content(content_urls))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "gitbook.py", line 214, in crawl_main_content
    await asyncio.gather(*tasks)
  File "gitbook.py", line 228, in gettext
    print("crawling : ", url)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-49: ordinal not in range(128)
```

**Comment by fuergaosi233** [comment]
第二个报错像是终端不支持unicode 
请尝试打印一下unicode编码字符
```python
python -c 'print(u"\u2122");'
```

**Comment by thinkycx** [comment]
加了环境变了解决。
![image](https://user-images.githubusercontent.com/13138128/56340134-96623600-61e3-11e9-9f74-7b3e2e863042.png)

但是生成两个pdf时依然报错：
```
$ PYTHONIOENCODING=utf-8 python3 gitbook.py http://self-publishing.ebookchain.org
crawling :  http://self-publishing.ebookchain.org/3-如何打造自己的平台？/2-Summary的使用.html
//[...]
done :  http://self-publishing.ebookchain.org/1-干嘛要写书？/2-写书的好处/readme.html
crawl : all done!
Traceback (most recent call last):
  File "gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 205, in run
    self.write_pdf(self.fname, html_text, css_text)
  File "gitbook.py", line 246, in write_pdf
    with open(htmlname, 'w', encoding='utf-8') as f:
UnicodeEncodeError: 'ascii' codec can't encode character '\u7528' in position 9: ordinal not in range(128)
```

```
$ PYTHONIOENCODING=utf-8 python3 gitbook.py http://hukai.me/android-training-course-in-chinese/
crawling :  http://hukai.me/android-training-course-in-chinese/graphics/opengl/index.html
//[...]
done :  http://hukai.me/android-training-course-in-chinese/ux/implement-nav/ancestral.html
crawl : all done!
Traceback (most recent call last):
  File "gitbook.py", line 303, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 205, in run
    self.write_pdf(self.fname, html_text, css_text)
  File "gitbook.py", line 246, in write_pdf
    with open(htmlname, 'w', encoding='utf-8') as f:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-24: ordinal not in range(128)
```
