### ISSUE TITLE
可以增加单线程吗，经常报域名解析错误

### ISSUE THREAD

**Issue by dreamer2q** [fuergaosi233/gitbook2pdf#59]
我不是很清楚这个错误是否因为并发过多引起的，
不过我觉得脚本可以增加对错误的友好处理，而不是直接崩溃
此外，如果可以保存上次爬取失败的进度，下次不用从新开始会更好吧。

**Comment by dreamer2q** [comment]
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 789, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gitbook.py", line 306, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 195, in run
    loop.run_until_complete(self.crawl_main_content(content_urls))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "gitbook.py", line 217, in crawl_main_content
    await asyncio.gather(*tasks)
  File "gitbook.py", line 236, in gettext
    metatext = await request(url, self.headers)
  File "gitbook.py", line 16, in request
    async with session.get(url, headers=headers, timeout=timeout) as resp:
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host astaxie.gitbooks.io:443 ssl:None [Temporary failure in name resolution]
```

**Comment by dreamer2q** [comment]
此外，好不容易爬成功一次，产生`pdf`的时候会报`The read operation timed out`错误

```bash
crawl : all done!
exception calling callback for <Future at 0x7f5be81d89e8 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
exception calling callback for <Future at 0x7f5be81d8ba8 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at /usr/local/lib/python3.7/dist-packages/aiohttp/connector.py:825> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348, <TaskWakeupMethWrapper object at 0x7f5be81df828>()]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.7/asyncio/tasks.py:776]>
Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at /usr/local/lib/python3.7/dist-packages/aiohttp/connector.py:825> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.7/asyncio/futures.py:348, <TaskWakeupMethWrapper object at 0x7f5be81dfb28>()]> cb=[shield.<locals>._done_callback() at /usr/lib/python3.7/asyncio/tasks.py:776]>
Generating pdf,please wait patiently
Traceback (most recent call last):
  File "gitbook.py", line 306, in <module>
    Gitbook2PDF(url).run()
  File "gitbook.py", line 208, in run
    self.write_pdf(self.fname, html_text, css_text)
  File "gitbook.py", line 252, in write_pdf
    tmphtml.write_pdf(fname, stylesheets=[tmpcss])
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/__init__.py", line 198, in write_pdf
    font_config=font_config).write_pdf(
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/__init__.py", line 159, in render
    font_config)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/document.py", line 355, in _render
    html.base_url, target_collector)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/formatting_structure/build.py", line 53, in build_formatting_structure
    target_collector)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/formatting_structure/build.py", line 169, in element_to_box
    target_collector, state))
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/formatting_structure/build.py", line 169, in element_to_box
    target_collector, state))
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/formatting_structure/build.py", line 169, in element_to_box
    target_collector, state))
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/formatting_structure/build.py", line 192, in element_to_box
    return html.handle_element(element, box, get_image_from_uri, base_url)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/html.py", line 88, in handle_element
    element, box, get_image_from_uri, base_url)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/html.py", line 132, in handle_img
    image = get_image_from_uri(src)
  File "/usr/local/lib/python3.7/dist-packages/weasyprint/images.py", line 183, in get_image_from_uri
    string = result['file_obj'].read()
  File "/usr/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/gzip.py", line 469, in read
    buf = self._fp.read(io.DEFAULT_BUFFER_SIZE)
  File "/usr/lib/python3.7/gzip.py", line 91, in read
    self.file.read(size-self._length+read)
  File "/usr/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 491, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.7/http/client.py", line 591, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/lib/python3.7/http/client.py", line 636, in _safe_readinto
    n = self.fp.readinto(mvb)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by fuergaosi233** [comment]
会考虑重写的，增加多线程的爬取
