### ISSUE TITLE
lxml.etree.SerialisationError: IO_ENCODER

### ISSUE THREAD

**Issue by wbvguo** [fuergaosi233/gitbook2pdf#79]
Traceback (most recent call last):
  File "gitbook.py", line 5, in <module>
    Gitbook2PDF(url).run()
  File "/mnt/c/Apps/Ubuntu/code/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 198, in run
    loop.run_until_complete(self.crawl_main_content(content_urls))
  File "/mnt/c/Apps/Ubuntu/apps/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/c/Apps/Ubuntu/code/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 220, in crawl_main_content
    await asyncio.gather(*tasks)
  File "/mnt/c/Apps/Ubuntu/code/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 241, in gettext
    text = ChapterParser(metatext, title, level, ).parser()
  File "/mnt/c/Apps/Ubuntu/code/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 105, in parser
    return html.unescape(ET.tostring(context).decode())
  File "src/lxml/etree.pyx", line 3437, in lxml.etree.tostring
  File "src/lxml/serializer.pxi", line 139, in lxml.etree._tostring
  File "src/lxml/serializer.pxi", line 199, in lxml.etree._raiseSerialisationError
lxml.etree.SerialisationError: IO_ENCODER

Besides, may I ask if you have plan to add some feature like `save html to PDFs`, this feature might make life easier.

**Comment by FloodLin** [comment]
I have the same problem.


> retrying :  https://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/prog-io.html
> Traceback (most recent call last):
>   File "gitbook.py", line 5, in <module>
>     Gitbook2PDF(url).run()
>   File "/home/flood/soft/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 198, in run
>     loop.run_until_complete(self.crawl_main_content(content_urls))
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/home/flood/soft/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 220, in crawl_main_content
>     await asyncio.gather(*tasks)
>   File "/home/flood/soft/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 241, in gettext
>     text = ChapterParser(metatext, title, level, ).parser()
>   File "/home/flood/soft/gitbook2pdf/gitbook2pdf/gitbook2pdf.py", line 105, in parser
>     return html.unescape(ET.tostring(context).decode())
>   File "src/lxml/etree.pyx", line 3437, in lxml.etree.tostring
>   File "src/lxml/serializer.pxi", line 139, in lxml.etree._tostring
>   File "src/lxml/serializer.pxi", line 199, in lxml.etree._raiseSerialisationError
> lxml.etree.SerialisationError: IO_ENCODER

**Comment by acheng-floyd** [comment]
reinstall lxml package could resolve this problem，in my case on centos7 , i use lxml4.2 
pip3.7 uninstall lxml && pip3.7 install lxml==4.2
