### ISSUE TITLE
运行pip install -r requirements.txt出错

### ISSUE THREAD

**Issue by kensinxie** [fuergaosi233/gitbook2pdf#90]
[root@localhost gitbook2pdf-master]# pip install -r requirements.txt
Collecting aiohttp==3.7.4 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7a/95/eb60aaad7943e18c9d091de93c9b0b5ed40aa67c7d5e3c5ee9b36f100a38/aiohttp-3.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xOdctz/aiohttp/setup.py", line 16
        print("Install submodules when building from git clone", file=sys.stderr)
                                                                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xOdctz/aiohttp/
You are using pip version 8.1.2, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

请问各位大神，我应该怎么做呢？

**Comment by kensinxie** [comment]
Google了一下发现centos中默认使用的仍然是py2，升级py3就好了。但注意centOS中的yum仍然依赖于py2
